---
title: "NZ_Homework1"
author: "Nicolas Zapata"
date: "2025-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir="~/projects/eco_genomics_2025/population_genomics/myresults/ANGSD/PCA_ADMIX/")
```

Load necesary libraries

```{r}

library(ggplot2)
library(ggpubr)

```

PCA

```{r}

# For K=2
COV_K2 <- as.matrix(read.table("RSBS_poly_K2.cov"))

PCA2 <- eigen(COV_K2)

# For K=3

COV_K3 <- as.matrix(read.table("RSBS_poly_K3.cov"))

PCA3 <- eigen(COV_K3)

# For K=4

COV_K4 <- as.matrix(read.table("RSBS_poly_K4.cov"))

PCA4 <- eigen(COV_K4)

# For K=5
COV_K5 <- as.matrix(read.table("RSBS_poly_K5.cov"))

PCA5 <- eigen(COV_K5)

```

Var

```{r}
var_K2 <- round(PCA2$values/sum(PCA2$values),3)

var_K2[1:3]

barplot(var_K2, 
        xlab="Eigenvalues of the PCA2", 
        ylab="Proportion of variance explained")
```

```{r}
var_K3 <- round(PCA3$values/sum(PCA3$values),3)

var_K3[1:3]

barplot(var_K3, 
        xlab="Eigenvalues of the PCA3", 
        ylab="Proportion of variance explained")
```

```{r}
var_K4 <- round(PCA4$values/sum(PCA4$values),3)

var_K4[1:3]

barplot(var_K4, 
        xlab="Eigenvalues of the PCA4", 
        ylab="Proportion of variance explained")
```

```{r}
var_K5 <- round(PCA5$values/sum(PCA5$values),3)

var_K5[1:3]

barplot(var_K5, 
        xlab="Eigenvalues of the PCA5", 
        ylab="Proportion of variance explained")
```

```{r}
# K2

names <- read.table("RSBS_bam.list")
names <- unlist(strsplit(basename(as.character(names[,1])), split = ".sorted.rmdup.bam"))
split = strsplit(names, "_")
pops <- data.frame(names[1:113], do.call(rbind, split[1:113]))
names(pops) = c("Ind", "Pop", "Row", "Col")

data=as.data.frame(PCA2$vectors)
data=data[,c(1:3)]
data= cbind(data, pops)

```

```{r}
# K3

names <- read.table("RSBS_bam.list")
names <- unlist(strsplit(basename(as.character(names[,1])), split = ".sorted.rmdup.bam"))
split = strsplit(names, "_")
pops <- data.frame(names[1:113], do.call(rbind, split[1:113]))
names(pops) = c("Ind", "Pop", "Row", "Col")

data=as.data.frame(PCA3$vectors)
data=data[,c(1:3)]
data= cbind(data, pops)

```

```{r}
# K4
names <- read.table("RSBS_bam.list")
names <- unlist(strsplit(basename(as.character(names[,1])), split = ".sorted.rmdup.bam"))
split = strsplit(names, "_")
pops <- data.frame(names[1:113], do.call(rbind, split[1:113]))
names(pops) = c("Ind", "Pop", "Row", "Col")

data=as.data.frame(PCA4$vectors)
data=data[,c(1:3)]
data= cbind(data, pops)

```

```{r}

# K5
names <- read.table("RSBS_bam.list")
names <- unlist(strsplit(basename(as.character(names[,1])), split = ".sorted.rmdup.bam"))
split = strsplit(names, "_")
pops <- data.frame(names[1:113], do.call(rbind, split[1:113]))
names(pops) = c("Ind", "Pop", "Row", "Col")

data=as.data.frame(PCA5$vectors)
data=data[,c(1:3)]
data= cbind(data, pops)

```


```{r}

ggscatter(data, x = "V1", y = "V2",
          color = "Pop",
          mean.point = TRUE,
          star.plot = TRUE,
          main="Red spruce-Black spruce genetic PCA") +
  theme_bw(base_size = 13, base_family = "Times") +
  labs(x = paste0("PC1: (",var_K2[1]*100,"%)"), y = paste0("PC2: (",var_K2[2]*100,"%)"))


```


```{r}

ggscatter(data, x = "V1", y = "V2",
          color = "Pop",
          mean.point = TRUE,
          star.plot = TRUE,
          main="Red spruce-Black spruce genetic PCA") +
  theme_bw(base_size = 13, base_family = "Times") +
  labs(x = paste0("PC1: (",var_K3[1]*100,"%)"), y = paste0("PC2: (",var_K3[2]*100,"%)"))


```

```{r}

ggscatter(data, x = "V1", y = "V2",
          color = "Pop",
          mean.point = TRUE,
          star.plot = TRUE,
          main="Red spruce-Black spruce genetic PCA") +
  theme_bw(base_size = 13, base_family = "Times") +
  labs(x = paste0("PC1: (",var_K4[1]*100,"%)"), y = paste0("PC2: (",var_K4[2]*100,"%)"))

```


```{r}

ggscatter(data, x = "V1", y = "V2",
          color = "Pop",
          mean.point = TRUE,
          star.plot = TRUE,
          main="Red spruce-Black spruce genetic PCA") +
  theme_bw(base_size = 13, base_family = "Times") +
  labs(x = paste0("PC1: (",var_K4[1]*100,"%)"), y = paste0("PC2: (",var_K4[2]*100,"%)"))

```




```{r}
# K2
q2 <- read.table("RSBS_poly_K2.admix.2.Q", sep=" ", header=F)

K2=dim(q2)[2] #Find the level of K modeled

## rank order the samples according to population code
ord2<-order(pops[,2])

# K3
q3 <- read.table("RSBS_poly_K3.admix.3.Q", sep=" ", header=F)

K3=dim(q3)[2] #Find the level of K modeled

## rank order the samples according to population code
ord3<-order(pops[,2])

#K=4

q4 <- read.table("RSBS_poly_K4.admix.4.Q", sep=" ", header=F)

K4=dim(q4)[2] #Find the level of K modeled

## rank order the samples according to population code
ord4<-order(pops[,2])

# K=5

q5 <- read.table("RSBS_poly_K5.admix.5.Q", sep=" ", header=F)

K5=dim(q5)[2] #Find the level of K modeled

## rank order the samples according to population code
ord5<-order(pops[,2])

```

Plot

```{r}

pdf("Admix_K2_K5.pdf",width=4, height = 8)
par(mfrow=c(4,1))

# for K=2

barplot(t(q2)[,ord2],
        #col=cols[1:K],
        col=c("black","red"),
        space=0,border=NA,
        xlab="Populations",ylab="Admixture proportions",
        main=paste0("Red Spruce-Black Spruce Admixture: K=",K2))
text(tapply(1:nrow(pops),pops[ord2,2],mean),-0.05,unique(pops[ord2,2]),xpd=T,cex=0.75,srt=45)
abline(v=cumsum(sapply(unique(pops[ord2,2]),function(x){sum(pops[ord2,2]==x)})),col=1,lwd=1.2)


# for K=3

barplot(t(q3)[,ord3],
        #col=cols[1:K],
        col=c("black","red"),
        space=0,border=NA,
        xlab="Populations",ylab="Admixture proportions",
        main=paste0("Red Spruce-Black Spruce Admixture: K=",K3))
text(tapply(1:nrow(pops),pops[ord3,2],mean),-0.05,unique(pops[ord3,2]),xpd=T,cex=0.75,srt=45)
abline(v=cumsum(sapply(unique(pops[ord3,2]),function(x){sum(pops[ord3,2]==x)})),col=1,lwd=1.2)


#for K=4
barplot(t(q4)[,ord4],
        #col=cols[1:K],
        col=c("black","red"),
        space=0,border=NA,
        xlab="Populations",ylab="Admixture proportions",
        main=paste0("Red Spruce-Black Spruce Admixture: K=",K4))
text(tapply(1:nrow(pops),pops[ord4,2],mean),-0.05,unique(pops[ord4,2]),xpd=T,cex=0.75,srt=45)
abline(v=cumsum(sapply(unique(pops[ord4,2]),function(x){sum(pops[ord4,2]==x)})),col=1,lwd=1.2)


# for K=5
barplot(t(q5)[,ord5],
        #col=cols[1:K],
        col=c("black","red"),
        space=0,border=NA,
        xlab="Populations",ylab="Admixture proportions",
        main=paste0("Red Spruce-Black Spruce Admixture: K=",K5))
text(tapply(1:nrow(pops),pops[ord5,2],mean),-0.05,unique(pops[ord5,2]),xpd=T,cex=0.75,srt=45)
abline(v=cumsum(sapply(unique(pops[ord5,2]),function(x){sum(pops[ord5,2]==x)})),col=1,lwd=1.2)

dev.off()
```




